name: prueba_03
# 24/09/2023
on: 
  push:
   branches:  [ master, desarrollo ]

jobs:
  master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    
    steps:
      
     - uses: actions/checkout@v2
    
     - name: Ejecuta el script de compilacion 
       run: |
         ls -la
         echo "======================"
         echo "Master"
         echo "======================"

                
        
  desarrollo:
    if: ${{ github.ref == 'refs/heads/desarrollo' }}  
    runs-on: ubuntu-latest
    
    steps:
      
     - uses: actions/checkout@v2
    
     - name: Ejecuta el script de compilacion 
       run: |
         ls -la
         echo "======================"
         echo "desarrollo"
         echo "======================"

                
        
  reciclado:
   if: ${{ github.ref == 'refs/heads/desarrollo' }}
   uses: ./.pavachoquegamer/prueba_03/.github.com/pavachoquegamer/prueba_03/blob/master/.github/workflows/main.yml
